      - name: Resolve packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -project ChessElo.xcodeproj \
            -scheme "ChessElo"

      - name: Build
        run: |
          xcodebuild \
            -project ChessElo.xcodeproj \
            -scheme "ChessElo" \
            -destination 'generic/platform=iOS Simulator' \
            clean build
